/*
 * This file is generated by jOOQ.
*/
package com.ccbscf.learn.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff implements Serializable {

    private static final long serialVersionUID = 1283485813;

    private UInteger      id;
    private String        name;
    private Integer       gender;
    private String        img;
    private Integer       documentType;
    private String        documentNumber;
    private Integer       status;
    private String        createBy="";
    private LocalDateTime createAt=LocalDateTime.now();
    private String        updateBy="";
    private LocalDateTime updateAt=LocalDateTime.now();
    private String        deleteBy="";
    private LocalDateTime deleteAt=LocalDateTime.now();

    public Staff() {}

    public Staff(Staff value) {
        this.id = value.id;
        this.name = value.name;
        this.gender = value.gender;
        this.img = value.img;
        this.documentType = value.documentType;
        this.documentNumber = value.documentNumber;
        this.status = value.status;
        this.createBy = value.createBy;
        this.createAt = value.createAt;
        this.updateBy = value.updateBy;
        this.updateAt = value.updateAt;
        this.deleteBy = value.deleteBy;
        this.deleteAt = value.deleteAt;
    }

    public Staff(
        UInteger      id,
        String        name,
        Integer       gender,
        String        img,
        Integer       documentType,
        String        documentNumber,
        Integer       status,
        String        createBy,
        LocalDateTime createAt,
        String        updateBy,
        LocalDateTime updateAt,
        String        deleteBy,
        LocalDateTime deleteAt
    ) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.img = img;
        this.documentType = documentType;
        this.documentNumber = documentNumber;
        this.status = status;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.deleteBy = deleteBy;
        this.deleteAt = deleteAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getImg() {
        return this.img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public Integer getDocumentType() {
        return this.documentType;
    }

    public void setDocumentType(Integer documentType) {
        this.documentType = documentType;
    }

    public String getDocumentNumber() {
        return this.documentNumber;
    }

    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    public String getDeleteBy() {
        return this.deleteBy;
    }

    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    public LocalDateTime getDeleteAt() {
        return this.deleteAt;
    }

    public void setDeleteAt(LocalDateTime deleteAt) {
        this.deleteAt = deleteAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staff (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(gender);
        sb.append(", ").append(img);
        sb.append(", ").append(documentType);
        sb.append(", ").append(documentNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(deleteBy);
        sb.append(", ").append(deleteAt);

        sb.append(")");
        return sb.toString();
    }
}
