/*
 * This file is generated by jOOQ.
*/
package com.ccbscf.learn;


import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;
}
